name: Replace yournextstore with amoha jewellery

on:
  workflow_dispatch:   # run manually from Actions tab

jobs:
  replace:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Replace "yournextstore" with "amoha jewellery"
        run: |
          git grep -l 'yournextstore' | grep -v '.github/workflows' | xargs sed -i 's/yournextstore/amoha jewellery/g'

      - name: Commit Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Automated rename: yournextstore → amoha jewellery" || echo "No changes to commit"
          git push
